/// <reference types="node" />
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { beforeAll, describe, expect, it, vi } from 'vitest'

// The module under test loads pdf-lib and crypto through window.require, which
// only exists in the Electron renderer.
const nodeRequire = createRequire(import.meta.url)
vi.stubGlobal('window', { require: nodeRequire })

const pdfLib = nodeRequire('pdf-lib') as typeof import('pdf-lib')
const { PDFArray, PDFDocument, PDFName, PDFDict, PDFHexString, PDFRawStream, PDFString, decodePDFRawStream } =
  pdfLib

let mod: typeof import('@/utils/pdfEncryption')
beforeAll(async () => {
  mod = await import('@/utils/pdfEncryption')
})

// Generated by scripts/make-encryption-fixtures.py from plain.pdf.
function fixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(new URL(`./fixtures/encryption/${name}`, import.meta.url)))
}

interface Snapshot {
  pageContents: string[]
  outlineTitles: string[]
  infoTitle: string | undefined
}

// Decoded page content plus a few text strings: the parts that are encrypted
// in the fixtures and must round-trip byte-for-byte to plain.pdf's.
async function snapshot(bytes: Uint8Array): Promise<Snapshot> {
  const doc = await PDFDocument.load(bytes, { updateMetadata: false })
  const pageContents = doc.getPages().map((page) => {
    const contents = page.node.Contents()
    const streams: import('pdf-lib').PDFRawStream[] = []
    if (contents instanceof PDFRawStream) streams.push(contents)
    if (contents instanceof PDFArray) {
      for (let i = 0; i < contents.size(); i++) streams.push(contents.lookup(i, PDFRawStream))
    }
    return streams.map((s) => Buffer.from(decodePDFRawStream(s).decode()).toString('latin1')).join('')
  })
  const outlineTitles: string[] = []
  const outlines = doc.catalog.lookupMaybe(PDFName.of('Outlines'), PDFDict)
  let item = outlines?.lookupMaybe(PDFName.of('First'), PDFDict)
  while (item) {
    const title = item.lookup(PDFName.of('Title'))
    if (title instanceof PDFString || title instanceof PDFHexString) outlineTitles.push(title.decodeText())
    item = item.lookupMaybe(PDFName.of('Next'), PDFDict)
  }
  return { pageContents, outlineTitles, infoTitle: doc.getTitle() }
}

const OWNER_LOCKED = [
  'mupdf-rc4-40.pdf',
  'mupdf-rc4-128.pdf',
  'mupdf-aes-128-objstm.pdf',
  'mupdf-aes-256-objstm.pdf',
  'pypdf-aes-128.pdf',
  'pypdf-aes-256-r5.pdf',
]

describe('decryptPdf', () => {
  let expected: Snapshot
  beforeAll(async () => {
    expected = await snapshot(fixture('plain.pdf'))
    expect(expected.pageContents).toHaveLength(2)
    const hello = Buffer.from('Hello encrypted page 1', 'latin1').toString('hex')
    expect(expected.pageContents[0]).toContain(`<${hello}>`)
    expect(expected.outlineTitles).toEqual(['Chapter One', 'Chapter Two'])
    expect(expected.infoTitle).toBe('Secret Title')
  })

  it.each(OWNER_LOCKED)('recovers the plaintext of %s with no password', async (name) => {
    await expect(PDFDocument.load(fixture(name))).rejects.toThrow(/encrypted/)
    const out = await mod.decryptPdf(fixture(name))
    expect(await snapshot(out)).toEqual(expected)
  })

  it('drops the /Encrypt entry so the output loads as a plain PDF', async () => {
    const out = await mod.decryptPdf(fixture('mupdf-aes-256-objstm.pdf'))
    const doc = await PDFDocument.load(out)
    expect(doc.isEncrypted).toBe(false)
  })

  it.each(['mupdf-rc4-128-user-password.pdf', 'mupdf-aes-256-user-password.pdf'])(
    'refuses %s without its password, and opens it with either password',
    async (name) => {
      await expect(mod.decryptPdf(fixture(name))).rejects.toBeInstanceOf(mod.PdfPasswordError)
      await expect(mod.decryptPdf(fixture(name), 'wrong')).rejects.toBeInstanceOf(mod.PdfPasswordError)
      expect(await snapshot(await mod.decryptPdf(fixture(name), 'secret'))).toEqual(expected)
      expect(await snapshot(await mod.decryptPdf(fixture(name), 'owner'))).toEqual(expected)
    },
  )
})

describe('loadPdfDocument', () => {
  it('loads unencrypted files unchanged', async () => {
    const { doc, decrypted } = await mod.loadPdfDocument(fixture('plain.pdf').buffer as ArrayBuffer)
    expect(decrypted).toBe(false)
    expect(doc.getPageCount()).toBe(2)
  })

  it('decrypts owner-locked files instead of throwing', async () => {
    const { doc, decrypted } = await mod.loadPdfDocument(fixture('mupdf-aes-128-objstm.pdf'))
    expect(decrypted).toBe(true)
    expect(doc.isEncrypted).toBe(false)
    expect(doc.getPageCount()).toBe(2)
  })
})
